FROM php:8.3-fpm

WORKDIR /var/www

# Instala dependencias del sistema
RUN apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip git unzip && \
    docker-php-ext-install pdo_mysql && \
    docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install gd

# Copia solo los archivos de dependencias primero
COPY composer.json composer.lock ./

# Instala Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Instala dependencias de PHP (esto se cachea si composer.json no cambia)
RUN composer install --no-dev --optimize-autoloader

# Ahora copia el resto del código fuente
COPY . .

CMD ["php-fpm"]
